INSERT INTO address VALUES(
    '25', /*Number*/
    'Rue de la Moselle', /*Street*/
    '', /*Additional Info*/
    (SELECT id_city
        FROM cities WHERE name LIKE 'Nancy' AND postcode LIKE '54000')
);
INSERT INTO dbo.person VALUES('Jean','Client','07-06-1977',SCOPE_IDENTITY());
INSERT INTO dbo.client VALUES(SCOPE_IDENTITY(),1); -- The 1 is the "available" value, when set to 0, the client is deleted but only keep for legal record
/*Query used to create a client with the address and person lines required*/
/*Here, the client's name is Jean CLIENT, he was born on the 7th of june 1977*/
/*The three queries can be put in separated classes for C++ implementation,
the developper just has to keep the IDs generated by the two first queries (as it is done here with
the SCOPE_IDENTITY() function) */