INSERT INTO address VALUES(
    '25', /*Number*/
    'Rue de la Moselle', /*Street*/
    '', /*Additional Info*/
    (SELECT id_city
        FROM cities WHERE name LIKE 'Nancy' AND postcode LIKE '54000')
);
INSERT INTO dbo.person VALUES('Jean','Fondateur','07-06-1977',SCOPE_IDENTITY());
INSERT INTO dbo.employees VALUES('09-19-2022',SCOPE_IDENTITY(),NULL,1); -- The first value is the employee's hire date, here, he was hired on the 19th of september 2022
																		-- The third value is the ID of his superior, here the employee has no superior
																		-- The fourth value is the "available" value, when set to 0, the employee is deleted but only keep for legal record
/*Query used to create an employee with the address and person lines required*/
/*Here, the employee's name is Jean FONDATEUR, he was born on the 7th of june 1977*/
/*The three queries can be put in separated classes for C++ implementation,
the developper just has to keep the IDs generated by the two first queries (as it is done here with
the SCOPE_IDENTITY() function) */
